version: 1.20.1.{build}

environment:
    matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        GEN: "Visual Studio 15 2017"
        ARCH: Win32
        CFG: Release
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        GEN: "Visual Studio 15 2017"
        ARCH: x64
        CFG: Release

build_script:
    - cd build
    - cmake -G "%GEN%" -A %ARCH% -DALSOFT_BUILD_ROUTER=ON -DALSOFT_REQUIRE_WINMM=ON -DALSOFT_REQUIRE_DSOUND=ON -DALSOFT_REQUIRE_WASAPI=ON -DALSOFT_EMBED_HRTF_DATA=YES ..
    - cmake --build . --config %CFG% --clean-first
